import type { ProjectPlan } from '@/types';
import type { ReportConfig } from '@/types/report';
import MarkdownIt from 'markdown-it';
import { getFormattingPreset } from '@/presets/formatting';
import { PAGE_SIZES, LINE_SPACING, DEFAULT_SPACING } from '@/constants/docx';
import { parseMarkdownTokensToDocx } from './markdownParser';

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportPlanAsDocx = async (plan: ProjectPlan, config: ReportConfig) => {
  try {
    // Dynamic import with retry logic
    let docx;
    let retryCount = 0;
    const maxRetries = 3;

    while (retryCount < maxRetries) {
      try {
        docx = await import('docx');
        break; // Success, exit retry loop
      } catch (_importError) {
        retryCount++;
        if (retryCount >= maxRetries) {
          throw new Error(
            'Failed to load DOCX library after multiple attempts. Please refresh the page.',
          );
        }
        // Wait before retry (exponential backoff)
        await new Promise((resolve) => setTimeout(resolve, 1000 * retryCount));
      }
    }

    if (!docx) {
      throw new Error('Failed to load DOCX library');
    }

    const {
      Document,
      Packer,
      Paragraph,
      HeadingLevel,
      TextRun,
      PageBreak,
      Table,
      TableCell,
      TableRow,
      WidthType,
      AlignmentType,
    } = docx;

    console.log('🚀 Starting DOCX export for project:', config.title);

    // Get formatting options from config or use theme preset
    const formatting = config.formatting || getFormattingPreset(config.theme);
    console.log(`📐 Using formatting: ${config.theme} theme`);

    const docSections: any[] = [];

    // Sort sections just in case, though usually config.sections matches UI order
    // Filtering enabled sections
    const enabledSections = config.sections.filter((s) => s.isEnabled);

    for (const section of enabledSections) {
      // --- 1. Title Page ---
      if (section.id === 'title') {
        docSections.push(
          new Paragraph({
            text: config.title, // Use title from config
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { before: 2400, after: 400 }, // Added spacing
          }),
          new Paragraph({
            text: 'Project Plan',
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `Generated by Plannify AI on ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { before: 1200 }, // Bottom spacing
          }),
          new Paragraph({ children: [new PageBreak()] }),
        );
        continue;
      }

      // --- 2. Table of Contents ---
      if (section.id === 'toc') {
        // Basic manual TOC for now, or Docx's dynamic TOC if needed
        // For simplicity, we just add the list of sections
        docSections.push(
          new Paragraph({ text: 'Table of Contents', heading: HeadingLevel.HEADING_1 }),
        );

        enabledSections
          .filter((s) => s.id !== 'title' && s.id !== 'toc')
          .forEach((s, index) => {
            docSections.push(
              new Paragraph({
                text: `${index + 1}. ${s.title}`,
                spacing: { after: 120 },
              }),
            );
          });

        docSections.push(new Paragraph({ children: [new PageBreak()] }));
        continue;
      }

      // --- 3. Dynamic/Custom Content Handling ---

      // Header for the section
      docSections.push(new Paragraph({ text: section.title, heading: HeadingLevel.HEADING_1 }));

      // If user provided custom content override or it's a 'text' type
      if (section.content) {
        // Parse Markdown content
        const md = new MarkdownIt();
        const tokens = md.parse(section.content, {});

        // Use improved markdown parser with proper typing
        const parsedParagraphs = parseMarkdownTokensToDocx(
          tokens,
          Paragraph,
          TextRun,
          formatting.documentFont.size, // Pass font size from formatting
        );
        docSections.push(...parsedParagraphs);
      } else if (section.type === 'dynamic') {
        // Fallback to standard data generation if no Custom Content
        switch (section.dataSource) {
          case 'keyComponents':
            plan.keyComponents.forEach((component) =>
              docSections.push(new Paragraph({ text: component, bullet: { level: 0 } })),
            );
            break;
          case 'recommendedTechStack': {
            const techStackTable = new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  children: [
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: 'Category', bold: true })],
                        }),
                      ],
                    }),
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: 'Technologies', bold: true })],
                        }),
                      ],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Frontend')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.frontend.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Backend')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.backend.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Database')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.database.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Other')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.other.join(', '))],
                    }),
                  ],
                }),
              ],
            });
            docSections.push(techStackTable);
            break;
          }
          case 'detailedFeatures':
            plan.detailedFeatures.forEach((feature, index) => {
              docSections.push(
                new Paragraph({
                  text: `${index + 1}. ${feature.name}`,
                  heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph(feature.description),
              );
              // Add main functions list
              feature.mainFunctions.forEach((func) =>
                docSections.push(new Paragraph({ text: func, bullet: { level: 0 } })),
              );
            });
            break;
          case 'developmentPlan':
            // ... Timeline logic
            if (plan.developmentPlan.milestones.length > 0) {
              const timelineTable = new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: [
                  new TableRow({
                    children: [
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Milestone', bold: true })],
                          }),
                        ],
                      }),
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Duration', bold: true })],
                          }),
                        ],
                      }),
                    ],
                  }),
                  ...plan.developmentPlan.milestones.map(
                    (milestone) =>
                      new TableRow({
                        children: [
                          new TableCell({ children: [new Paragraph(milestone.name)] }),
                          new TableCell({
                            children: [new Paragraph(`${milestone.estimatedDurationWeeks} weeks`)],
                          }),
                        ],
                      }),
                  ),
                ],
              });
              docSections.push(timelineTable);
            }
            break;
          case 'potentialChallenges':
            plan.potentialChallenges.forEach((challenge) =>
              docSections.push(new Paragraph({ text: challenge, bullet: { level: 0 } })),
            );
            break;
          default:
            docSections.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: '[No data source linked]',
                    italics: true,
                  }),
                ],
              }),
            );
        }
      }

      // Add page break after each section (except the last one)
      docSections.push(new Paragraph({ children: [new PageBreak()] }));
    }

    const doc = new Document({
      styles: {
        paragraphStyles: [
          {
            id: 'DefaultStyle',
            name: 'Default Style',
            basedOn: 'Normal',
            next: 'Normal',
            run: {
              size: formatting.documentFont.size,
              font: formatting.documentFont.family,
              color: formatting.documentFont.color || '000000',
              bold: formatting.documentFont.bold,
              italics: formatting.documentFont.italic,
            },
            paragraph: {
              spacing: {
                after: DEFAULT_SPACING.AFTER,
                line: LINE_SPACING.ONE_AND_HALF,
              },
            },
          },
          {
            id: 'Title',
            name: 'Title',
            run: {
              size: formatting.headings.title.size,
              font: formatting.headings.title.family,
              color: formatting.headings.title.color || '000000',
              bold: formatting.headings.title.bold !== false,
            },
            paragraph: {
              spacing: {
                before: formatting.headings.title.spacingBefore || 0,
                after: formatting.headings.title.spacingAfter || 400,
              },
            },
          },
          {
            id: 'Heading1',
            name: 'Heading 1',
            run: {
              size: formatting.headings.h1.size,
              font: formatting.headings.h1.family,
              color: formatting.headings.h1.color || '000000',
              bold: formatting.headings.h1.bold !== false,
            },
            paragraph: {
              spacing: {
                before: formatting.headings.h1.spacingBefore || 600,
                after: formatting.headings.h1.spacingAfter || 300,
              },
            },
          },
          {
            id: 'Heading2',
            name: 'Heading 2',
            run: {
              size: formatting.headings.h2.size,
              font: formatting.headings.h2.family,
              color: formatting.headings.h2.color || '000000',
              bold: formatting.headings.h2.bold !== false,
            },
            paragraph: {
              spacing: {
                before: formatting.headings.h2.spacingBefore || 400,
                after: formatting.headings.h2.spacingAfter || 200,
              },
            },
          },
          {
            id: 'Heading3',
            name: 'Heading 3',
            run: {
              size: formatting.headings.h3.size,
              font: formatting.headings.h3.family,
              color: formatting.headings.h3.color || '000000',
              bold: formatting.headings.h3.bold !== false,
            },
            paragraph: {
              spacing: {
                before: formatting.headings.h3.spacingBefore || 300,
                after: formatting.headings.h3.spacingAfter || 150,
              },
            },
          },
        ],
      },
      sections: [
        {
          properties: {
            page: {
              margin: formatting.margins,
              // Set page size based on formatting.pageSize
              ...(formatting.pageSize === 'a4'
                ? {
                    width: PAGE_SIZES.A4.width,
                    height: PAGE_SIZES.A4.height,
                  }
                : {
                    width: PAGE_SIZES.LETTER.width,
                    height: PAGE_SIZES.LETTER.height,
                  }),
            },
          },
          children: docSections,
        },
      ],
    });

    console.log('📄 Generating DOCX document...');
    const blob = await Packer.toBlob(doc);
    const filename = `${config.title.replace(/[^a-zA-Z0-9]/g, '_')}_Report.docx`;

    downloadBlob(blob, filename);
    console.log('✅ DOCX export completed successfully');
  } catch (error) {
    console.error('❌ DOCX export failed:', error);

    // Provide user-friendly error messages
    let errorMessage = 'Failed to export DOCX document.';

    if (error instanceof Error) {
      if (error.message.includes('import')) {
        errorMessage = 'Failed to load DOCX library. Please refresh and try again.';
      } else if (error.message.includes('formatting')) {
        errorMessage = 'Invalid formatting options. Please check your theme settings.';
      } else {
        errorMessage = `Export failed: ${error.message}`;
      }
    }

    alert(errorMessage);
  }
};

// End of file
