import type { ProjectPlan } from './types';
import * as docx from 'docx';
import MarkdownIt from 'markdown-it';

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportPlanAsDocx = async (plan: ProjectPlan, projectName: string) => {
  if (typeof docx === 'undefined') {
    console.error('DOCX.js library is not loaded.');
    alert('Error: Document generation library is not available.');
    return;
  }

  const { Document, Packer, Paragraph, HeadingLevel, TextRun, PageBreak, Table, TableCell, TableRow, WidthType, AlignmentType } = docx;

  try {
    console.log('🚀 Starting DOCX export for project:', projectName);

    const sections: any[] = [];

    // Title Page
    sections.push(
      new Paragraph({
        text: projectName,
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER
      }),
      new Paragraph({
        text: 'Project Plan',
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER
      }),
      new Paragraph({
        text: `Generated by Plannify AI on ${new Date().toLocaleDateString('vi-VN')}`,
        alignment: AlignmentType.CENTER
      }),
      new Paragraph({ children: [new PageBreak()] })
    );

    // Table of Contents
    sections.push(
      new Paragraph({ text: 'Table of Contents', heading: HeadingLevel.HEADING_1 }),
      new Paragraph({ text: '1. Executive Summary' }),
      new Paragraph({ text: '2. Key Components' }),
      new Paragraph({ text: '3. Technology Stack' }),
      new Paragraph({ text: '4. Challenges & Opportunities' }),
      new Paragraph({ text: '5. Feature Specifications' }),
      new Paragraph({ text: '6. Development Timeline' }),
      new Paragraph({ children: [new PageBreak()] })
    );

    // Executive Summary
    sections.push(
      new Paragraph({ text: '1. Executive Summary', heading: HeadingLevel.HEADING_1 }),
      new Paragraph(plan.summary),
      new Paragraph({ children: [new PageBreak()] })
    );

    // Key Components
    sections.push(new Paragraph({ text: '2. Key Components', heading: HeadingLevel.HEADING_1 }));
    plan.keyComponents.forEach(component =>
      sections.push(new Paragraph({ text: component, bullet: { level: 0 } }))
    );
    sections.push(new Paragraph({ children: [new PageBreak()] }));

    // Technology Stack - Enhanced with Table
    sections.push(new Paragraph({ text: '3. Technology Stack', heading: HeadingLevel.HEADING_1 }));

    const techStackTable = new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: 'Category', run: { bold: true } })] }),
            new TableCell({ children: [new Paragraph({ text: 'Technologies', run: { bold: true } })] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Frontend')] }),
            new TableCell({ children: [new Paragraph(plan.recommendedTechStack.frontend.join(', '))] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Backend')] }),
            new TableCell({ children: [new Paragraph(plan.recommendedTechStack.backend.join(', '))] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Database')] }),
            new TableCell({ children: [new Paragraph(plan.recommendedTechStack.database.join(', '))] }),
          ],
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph('Other')] }),
            new TableCell({ children: [new Paragraph(plan.recommendedTechStack.other.join(', '))] }),
          ],
        }),
      ],
    });

    sections.push(techStackTable);
    sections.push(new Paragraph({ children: [new PageBreak()] }));

    // Challenges & Opportunities
    sections.push(new Paragraph({ text: '4. Challenges & Opportunities', heading: HeadingLevel.HEADING_1 }));

    sections.push(new Paragraph({ text: 'Potential Challenges', heading: HeadingLevel.HEADING_2 }));
    plan.potentialChallenges.forEach(challenge =>
      sections.push(new Paragraph({ text: challenge, bullet: { level: 0 } }))
    );

    sections.push(new Paragraph({ text: 'Potential Opportunities', heading: HeadingLevel.HEADING_2 }));
    plan.potentialOpportunities.forEach(opportunity =>
      sections.push(new Paragraph({ text: opportunity, bullet: { level: 0 } }))
    );

    sections.push(new Paragraph({ children: [new PageBreak()] }));

    // Feature Specifications - Enhanced
    sections.push(new Paragraph({ text: '5. Feature Specifications', heading: HeadingLevel.HEADING_1 }));

    plan.detailedFeatures.forEach((feature, index) => {
      sections.push(new Paragraph({
        text: `${index + 1}. ${feature.name}`,
        heading: HeadingLevel.HEADING_2
      }));

      sections.push(new Paragraph(feature.description));

      // Main Functions
      sections.push(new Paragraph({ text: 'Main Functions', heading: HeadingLevel.HEADING_3 }));
      feature.mainFunctions.forEach(func =>
        sections.push(new Paragraph({ text: func, bullet: { level: 0 } }))
      );

      // Sub-Features
      if (feature.subFeatures.length > 0) {
        sections.push(new Paragraph({ text: 'Sub-Features', heading: HeadingLevel.HEADING_3 }));
        feature.subFeatures.forEach(subFeature =>
          sections.push(new Paragraph({ text: subFeature, bullet: { level: 1 } }))
        );
      }

      sections.push(new Paragraph({ text: '' })); // Spacer
    });

    sections.push(new Paragraph({ children: [new PageBreak()] }));

    // Development Timeline - Enhanced with Table
    sections.push(new Paragraph({ text: '6. Development Timeline', heading: HeadingLevel.HEADING_1 }));

    if (plan.developmentPlan.milestones.length > 0) {
      const timelineTable = new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          new TableRow({
            children: [
              new TableCell({ children: [new Paragraph({ text: 'Milestone', run: { bold: true } })] }),
              new TableCell({ children: [new Paragraph({ text: 'Description', run: { bold: true } })] }),
              new TableCell({ children: [new Paragraph({ text: 'Duration', run: { bold: true } })] }),
              new TableCell({ children: [new Paragraph({ text: 'Start Week', run: { bold: true } })] }),
            ],
          }),
          ...plan.developmentPlan.milestones.map(milestone =>
            new TableRow({
              children: [
                new TableCell({ children: [new Paragraph(milestone.name)] }),
                new TableCell({ children: [new Paragraph(milestone.description)] }),
                new TableCell({ children: [new Paragraph(`${milestone.estimatedDurationWeeks} weeks`)] }),
                new TableCell({ children: [new Paragraph(milestone.estimatedStartDate)] }),
              ],
            })
          ),
        ],
      });

      sections.push(timelineTable);

      // Detailed milestone breakdown
      sections.push(new Paragraph({ text: 'Milestone Details', heading: HeadingLevel.HEADING_2 }));

      plan.developmentPlan.milestones.forEach((milestone, index) => {
        sections.push(new Paragraph({
          text: `${index + 1}. ${milestone.name}`,
          heading: HeadingLevel.HEADING_3
        }));

        sections.push(new Paragraph(milestone.description));

        if (milestone.tasks.length > 0) {
          sections.push(new Paragraph({ text: 'Key Tasks:', run: { italics: true } }));
          milestone.tasks.forEach(task =>
            sections.push(new Paragraph({ text: task, bullet: { level: 0 } }))
          );
        }

        sections.push(new Paragraph({ text: '' }));
      });
    }

    // Create document with enhanced styling
    const doc = new Document({
      styles: {
        paragraphStyles: [
          {
            id: 'DefaultStyle',
            name: 'Default Style',
            basedOn: 'Normal',
            next: 'Normal',
            run: {
              size: 24, // 12pt
              font: 'Calibri',
            },
            paragraph: {
              spacing: {
                after: 200,
                line: 360, // 1.5 line spacing
              },
            },
          },
          {
            id: 'Title',
            name: 'Title',
            basedOn: 'Normal',
            run: {
              size: 36, // 18pt
              bold: true,
              font: 'Calibri',
            },
            paragraph: {
              spacing: {
                before: 1200,
                after: 600,
              },
            },
          },
          {
            id: 'Heading1',
            name: 'Heading 1',
            basedOn: 'Normal',
            run: {
              size: 32, // 16pt
              bold: true,
              font: 'Calibri',
              color: '1f2937',
            },
            paragraph: {
              spacing: {
                before: 800,
                after: 400,
              },
            },
          },
          {
            id: 'Heading2',
            name: 'Heading 2',
            basedOn: 'Normal',
            run: {
              size: 28, // 14pt
              bold: true,
              font: 'Calibri',
              color: '374151',
            },
            paragraph: {
              spacing: {
                before: 600,
                after: 300,
              },
            },
          },
          {
            id: 'Heading3',
            name: 'Heading 3',
            basedOn: 'Normal',
            run: {
              size: 26, // 13pt
              bold: true,
              font: 'Calibri',
              color: '4b5563',
            },
            paragraph: {
              spacing: {
                before: 400,
                after: 200,
              },
            },
          },
        ],
      },
      sections: [{
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              right: 1440,  // 1 inch
              bottom: 1440, // 1 inch
              left: 1440,   // 1 inch
            },
          },
        },
        children: sections
      }]
    });

    console.log('📄 Generating DOCX document...');
    const blob = await Packer.toBlob(doc);
    const filename = `${projectName.replace(/[^a-zA-Z0-9]/g, '_')}_Project_Plan.docx`;

    downloadBlob(blob, filename);
    console.log('✅ DOCX export completed successfully');

  } catch (error) {
    console.error('❌ DOCX export failed:', error);
    alert(`Export failed: ${error.message}`);
  }
};


export const exportReportAsDocx = async (reportContent: string, projectName: string, reportTitle: string) => {
    if (typeof docx === 'undefined') {
        console.error('DOCX.js library is not loaded.');
        alert('Error: Document generation library is not available.');
        return;
    }

    const { Document, Packer, Paragraph, HeadingLevel, PageBreak, TextRun } = docx;

    // Initialize markdown-it parser
    const md = new MarkdownIt();

    const children: any[] = [];
    children.push(new Paragraph({ text: reportTitle, heading: HeadingLevel.TITLE }));
    children.push(new Paragraph({ text: `For Project: ${projectName}`, heading: HeadingLevel.HEADING_3 }));
    children.push(new Paragraph({ text: '' })); // Spacer

    // Parse markdown content using markdown-it
    const tokens = md.parse(reportContent, {});
    let bulletStack: number[] = [];
    let currentBulletLevel = 0;

    for (let i = 0; i < tokens.length; i++) {
        const token = tokens[i];

        if (token.type === 'heading_open') {
            const level = parseInt(token.tag.substring(1));

            // Add page break before H2 headings (major sections)
            if (level === 2) {
                children.push(new Paragraph({ children: [new PageBreak()] }));
            }

            const nextToken = tokens[i + 1];
            if (nextToken && nextToken.type === 'inline') {
                const headingText = nextToken.content;

                switch (level) {
                    case 1:
                        children.push(new Paragraph({ text: headingText, heading: HeadingLevel.HEADING_1 }));
                        break;
                    case 2:
                        children.push(new Paragraph({ text: headingText, heading: HeadingLevel.HEADING_2 }));
                        break;
                    case 3:
                        children.push(new Paragraph({ text: headingText, heading: HeadingLevel.HEADING_3 }));
                        break;
                    case 4:
                        children.push(new Paragraph({ text: headingText, heading: HeadingLevel.HEADING_4 }));
                        break;
                    default:
                        children.push(new Paragraph({ text: headingText, heading: HeadingLevel.HEADING_1 }));
                }
            }
        } else if (token.type === 'paragraph_open') {
            const nextToken = tokens[i + 1];
            if (nextToken && nextToken.type === 'inline') {
                const paragraphText = nextToken.content;

                if (paragraphText.trim()) {
                    // Check for bold and italic formatting
                    const formattedChildren: any[] = [];
                    let lastEnd = 0;

                    // Simple regex to find **bold** and *italic* text
                    const boldItalicRegex = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
                    let match;

                    while ((match = boldItalicRegex.exec(paragraphText)) !== null) {
                        // Add text before formatting
                        if (match.index > lastEnd) {
                            formattedChildren.push(new TextRun({ text: paragraphText.substring(lastEnd, match.index) }));
                        }

                        const matchedText = match[0];
                        const cleanText = matchedText.replace(/^\*+|\*+$/g, '');

                        if (matchedText.startsWith('**')) {
                            formattedChildren.push(new TextRun({ text: cleanText, bold: true }));
                        } else if (matchedText.startsWith('*')) {
                            formattedChildren.push(new TextRun({ text: cleanText, italics: true }));
                        }

                        lastEnd = match.index + match[0].length;
                    }

                    // Add remaining text
                    if (lastEnd < paragraphText.length) {
                        formattedChildren.push(new TextRun({ text: paragraphText.substring(lastEnd) }));
                    }

                    children.push(new Paragraph({ children: formattedChildren }));
                } else if (paragraphText.trim() === '') {
                    children.push(new Paragraph({ text: '' })); // Empty line for spacing
                }
            }
        } else if (token.type === 'bullet_list_open' || token.type === 'ordered_list_open') {
            // Handle list start
            bulletStack.push(currentBulletLevel);
            currentBulletLevel = 0;
        } else if (token.type === 'list_item_open') {
            const nextToken = tokens[i + 1];
            if (nextToken && nextToken.type === 'paragraph_open') {
                const paraToken = tokens[i + 2];
                if (paraToken && paraToken.type === 'inline') {
                    children.push(new Paragraph({
                        text: paraToken.content,
                        bullet: { level: currentBulletLevel }
                    }));
                }
            }
            currentBulletLevel++;
        } else if (token.type === 'bullet_list_close' || token.type === 'ordered_list_close') {
            // Handle list end
            currentBulletLevel = bulletStack.pop() || 0;
        }
    }

    const doc = new Document({
        styles: {
            paragraphStyles: [
                {
                    id: 'DefaultStyle',
                    name: 'Default Style',
                    basedOn: 'Normal',
                    next: 'Normal',
                    run: {
                        size: 24, // 12pt font size
                        font: 'Calibri',
                    },
                    paragraph: {
                        spacing: {
                            after: 200, // line spacing
                        },
                    },
                },
                {
                    id: 'Title',
                    name: 'Title',
                    basedOn: 'Normal',
                    run: {
                        size: 32, // 16pt for title
                        bold: true,
                        font: 'Calibri',
                    },
                    paragraph: {
                        spacing: {
                            before: 1000,
                            after: 1000,
                        },
                    },
                },
                {
                    id: 'Heading1',
                    name: 'Heading 1',
                    basedOn: 'Normal',
                    run: {
                        size: 28, // 14pt for H1
                        bold: true,
                        font: 'Calibri',
                    },
                    paragraph: {
                        spacing: {
                            before: 800,
                            after: 400,
                        },
                    },
                },
                {
                    id: 'Heading2',
                    name: 'Heading 2',
                    basedOn: 'Normal',
                    run: {
                        size: 26, // 13pt for H2
                        bold: true,
                        font: 'Calibri',
                    },
                    paragraph: {
                        spacing: {
                            before: 600,
                            after: 300,
                        },
                    },
                },
                {
                    id: 'Heading3',
                    name: 'Heading 3',
                    basedOn: 'Normal',
                    run: {
                        size: 24, // 12pt for H3
                        italics: true,
                        font: 'Calibri',
                    },
                    paragraph: {
                        spacing: {
                            before: 400,
                            after: 200,
                        },
                    },
                },
            ],
        },
        sections: [{ children }]
    });
    const blob = await Packer.toBlob(doc);
    const filename = `${projectName.replace(/\s+/g, '_')}_${reportTitle.replace(/\s+/g, '_')}.docx`;
    downloadBlob(blob, filename);
};
