import type { ProjectPlan } from '../types';
import type { ReportConfig } from '../types/report';
// import * as docx from 'docx'; // Removed to ensure code splitting
import MarkdownIt from 'markdown-it';

const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportPlanAsDocx = async (plan: ProjectPlan, config: ReportConfig) => {
  try {
    const docx = await import('docx');
    const {
      Document,
      Packer,
      Paragraph,
      HeadingLevel,
      TextRun,
      PageBreak,
      Table,
      TableCell,
      TableRow,
      WidthType,
      AlignmentType,
    } = docx;

    console.log('🚀 Starting DOCX export for project:', config.title);

    const docSections: any[] = [];

    // Sort sections just in case, though usually config.sections matches UI order
    // Filtering enabled sections
    const enabledSections = config.sections.filter((s) => s.isEnabled);

    for (const section of enabledSections) {
      // --- 1. Title Page ---
      if (section.id === 'title') {
        docSections.push(
          new Paragraph({
            text: config.title, // Use title from config
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { before: 2400, after: 400 }, // Added spacing
          }),
          new Paragraph({
            text: 'Project Plan',
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            text: `Generated by Plannify AI on ${new Date().toLocaleDateString()}`,
            alignment: AlignmentType.CENTER,
            spacing: { before: 1200 }, // Bottom spacing
          }),
          new Paragraph({ children: [new PageBreak()] }),
        );
        continue;
      }

      // --- 2. Table of Contents ---
      if (section.id === 'toc') {
        // Basic manual TOC for now, or Docx's dynamic TOC if needed
        // For simplicity, we just add the list of sections
        docSections.push(
          new Paragraph({ text: 'Table of Contents', heading: HeadingLevel.HEADING_1 }),
        );

        enabledSections
          .filter((s) => s.id !== 'title' && s.id !== 'toc')
          .forEach((s, index) => {
            docSections.push(
              new Paragraph({
                text: `${index + 1}. ${s.title}`,
                spacing: { after: 120 },
              }),
            );
          });

        docSections.push(new Paragraph({ children: [new PageBreak()] }));
        continue;
      }

      // --- 3. Dynamic/Custom Content Handling ---

      // Header for the section
      docSections.push(new Paragraph({ text: section.title, heading: HeadingLevel.HEADING_1 }));

      // If user provided custom content override or it's a 'text' type
      if (section.content) {
        // Parse Markdown content
        const md = new MarkdownIt();
        const tokens = md.parse(section.content, {});

        // Re-use the markdown parsing logic from exportReportAsDocx
        // Note: Ideally extract this to a helper function
        const parsedParagraphs = parseMarkdownTokensToDocx(tokens, docx);
        docSections.push(...parsedParagraphs);
      } else if (section.type === 'dynamic') {
        // Fallback to standard data generation if no Custom Content
        switch (section.dataSource) {
          case 'keyComponents':
            plan.keyComponents.forEach((component) =>
              docSections.push(new Paragraph({ text: component, bullet: { level: 0 } })),
            );
            break;
          case 'recommendedTechStack': {
            const techStackTable = new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  children: [
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: 'Category', bold: true })],
                        }),
                      ],
                    }),
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [new TextRun({ text: 'Technologies', bold: true })],
                        }),
                      ],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Frontend')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.frontend.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Backend')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.backend.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Database')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.database.join(', '))],
                    }),
                  ],
                }),
                new TableRow({
                  children: [
                    new TableCell({ children: [new Paragraph('Other')] }),
                    new TableCell({
                      children: [new Paragraph(plan.recommendedTechStack.other.join(', '))],
                    }),
                  ],
                }),
              ],
            });
            docSections.push(techStackTable);
            break;
          }
          case 'detailedFeatures':
            plan.detailedFeatures.forEach((feature, index) => {
              docSections.push(
                new Paragraph({
                  text: `${index + 1}. ${feature.name}`,
                  heading: HeadingLevel.HEADING_2,
                }),
                new Paragraph(feature.description),
              );
              // Add main functions list
              feature.mainFunctions.forEach((func) =>
                docSections.push(new Paragraph({ text: func, bullet: { level: 0 } })),
              );
            });
            break;
          case 'developmentPlan':
            // ... Timeline logic
            if (plan.developmentPlan.milestones.length > 0) {
              const timelineTable = new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                rows: [
                  new TableRow({
                    children: [
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Milestone', bold: true })],
                          }),
                        ],
                      }),
                      new TableCell({
                        children: [
                          new Paragraph({
                            children: [new TextRun({ text: 'Duration', bold: true })],
                          }),
                        ],
                      }),
                    ],
                  }),
                  ...plan.developmentPlan.milestones.map(
                    (milestone) =>
                      new TableRow({
                        children: [
                          new TableCell({ children: [new Paragraph(milestone.name)] }),
                          new TableCell({
                            children: [new Paragraph(`${milestone.estimatedDurationWeeks} weeks`)],
                          }),
                        ],
                      }),
                  ),
                ],
              });
              docSections.push(timelineTable);
            }
            break;
          case 'potentialChallenges':
            plan.potentialChallenges.forEach((challenge) =>
              docSections.push(new Paragraph({ text: challenge, bullet: { level: 0 } })),
            );
            break;
          default:
            docSections.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: '[No data source linked]',
                    italics: true,
                  }),
                ],
              }),
            );
        }
      }

      // Add page break after each section (except the last one)
      docSections.push(new Paragraph({ children: [new PageBreak()] }));
    }

    const doc = new Document({
      styles: {
        paragraphStyles: [
          {
            id: 'DefaultStyle',
            name: 'Default Style',
            basedOn: 'Normal',
            next: 'Normal',
            run: {
              size: 24, // 12pt
              font: 'Calibri',
            },
            paragraph: {
              spacing: {
                after: 200,
                line: 360, // 1.5 line spacing
              },
            },
          },
          {
            id: 'Heading1',
            name: 'Heading 1',
            run: { size: 32, bold: true, color: '2E74B5' },
            paragraph: { spacing: { before: 600, after: 300 } },
          },
          {
            id: 'Heading2',
            name: 'Heading 2',
            run: { size: 28, bold: true, color: '2E74B5' },
            paragraph: { spacing: { before: 400, after: 200 } },
          },
        ],
      },
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 1440, // 1 inch
                right: 1440, // 1 inch
                bottom: 1440, // 1 inch
                left: 1440, // 1 inch
              },
            },
          },
          children: docSections,
        },
      ],
    });

    console.log('📄 Generating DOCX document...');
    const blob = await Packer.toBlob(doc);
    const filename = `${config.title.replace(/[^a-zA-Z0-9]/g, '_')}_Report.docx`;

    downloadBlob(blob, filename);
    console.log('✅ DOCX export completed successfully');
  } catch (error: any) {
    console.error('❌ DOCX export failed:', error);
    alert(`Export failed: ${error.message}`);
  }
};

// Type definitions for markdown parsing
interface MarkdownToken {
  type: string;
  content?: string;
  children?: MarkdownToken[];
  tag?: string;
}

interface DocxModule {
  Paragraph: any;
  TextRun: any;
  [key: string]: any;
}

// Helper to parse markdown tokens to DOCX elements
function parseMarkdownTokensToDocx(tokens: MarkdownToken[], docx: DocxModule): any[] {
  const { Paragraph, TextRun } = docx;
  const children: any[] = [];

  let currentParagraphChildren: any[] = [];

  tokens.forEach((token) => {
    if (token.type === 'inline') {
      // If token has children (formatting), try to interpret them, otherwise plain text
      if (token.children && token.children.length > 0) {
        // Simple state machine for bold/italic
        let isBold = false;
        let isItalic = false;

        token.children.forEach((child: MarkdownToken) => {
          if (child.type === 'text') {
            currentParagraphChildren.push(
              new TextRun({
                text: child.content,
                bold: isBold,
                italics: isItalic,
              }),
            );
          } else if (child.type === 'strong_open') {
            isBold = true;
          } else if (child.type === 'strong_close') {
            isBold = false;
          } else if (child.type === 'em_open') {
            isItalic = true;
          } else if (child.type === 'em_close') {
            isItalic = false;
          }
        });
      } else {
        currentParagraphChildren.push(new TextRun(token.content));
      }
    } else if (token.type === 'paragraph_close' || token.type === 'heading_close') {
      if (currentParagraphChildren.length > 0) {
        children.push(new Paragraph({ children: currentParagraphChildren }));
        currentParagraphChildren = [];
      }
    }
  });

  return children;
}

// Legacy function removed - use exportPlanAsDocx instead
// If you need this functionality, construct a ReportConfig and call exportPlanAsDocx

// End of file
