import type { TemplateData } from './types';

export const projectTemplates: TemplateData[] = [
  {
    projectName: "Standard Web App",
    shortDescription: "A modern, responsive web application with user authentication and a dynamic frontend.",
    businessGoals: "Engage users with a seamless web experience and capture market share.",
    technicalGoals: "Build a scalable and maintainable codebase.",
    targetUsers: ["General Public", "Web Users"],
    numberOfFeatures: 15,
    estimatedScale: "$25K-$75K",
    timeline: "4-6 months",
    coreRequirements: [
        { id: "1", description: "User registration and login (email/password, OAuth)", priority: 'High' },
        { id: "2", description: "User profile management", priority: 'High' },
        { id: "3", description: "Admin dashboard for user management", priority: 'Medium' },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Tailwind CSS"],
      backend: ["Node.js", "Express.js"],
      database: ["PostgreSQL"],
      otherTools: ["Vite", "Jest", "Docker"],
    },
    marketAnalysis: "The market for general web applications is vast. Success depends on finding a niche and providing a superior user experience compared to existing solutions.",
    competitors: ["Generic SaaS tools", "Custom-built internal apps"],
  },
  {
    projectName: "Mobile App Backend",
    shortDescription: "A robust backend service to support a mobile application, with a focus on API performance and security.",
    businessGoals: "Provide reliable data and services for the mobile app, ensuring a smooth user experience.",
    technicalGoals: "99.99% API uptime, sub-200ms response times, secure data storage.",
    targetUsers: ["Mobile App Users", "App Developers"],
    numberOfFeatures: 25,
    estimatedScale: "$50K-$150K",
    timeline: "6-9 months",
     coreRequirements: [
        { id: "1", description: "Secure RESTful API with JWT authentication", priority: 'High' },
        { id: "2", description: "Push notification service integration", priority: 'High' },
        { id: "3", description: "User data storage with encryption", priority: 'High' },
        { id: "4", description: "Image and media upload/storage", priority: 'Medium' },
    ],
    techStack: {
      frontend: [],
      backend: ["Python", "Django Rest Framework", "Celery"],
      database: ["PostgreSQL", "Redis"],
      otherTools: ["Docker", "S3 for storage", "Pytest"],
    },
    marketAnalysis: "The success of a mobile backend is directly tied to the success of the mobile app it serves. The market requires high reliability and scalability to handle fluctuating user loads.",
    competitors: ["Firebase", "Supabase", "AWS Amplify"],
  },
  {
    projectName: "Data Analytics Dashboard",
    shortDescription: "An internal dashboard for visualizing and analyzing business intelligence data from multiple sources.",
    businessGoals: "Empower business teams to make data-driven decisions by providing real-time insights.",
    technicalGoals: "Efficiently process large datasets, provide interactive visualizations.",
    targetUsers: ["Data Analysts", "Business Managers", "Executives"],
    numberOfFeatures: 30,
    estimatedScale: "$100K-$250K",
    timeline: "5-8 months",
    coreRequirements: [
        { id: "1", description: "Integration with multiple data sources (SQL, NoSQL, APIs)", priority: 'High' },
        { id: "2", description: "Customizable and interactive charts and graphs", priority: 'High' },
        { id: "3", description: "Role-based access control to dashboards", priority: 'Medium' },
        { id: "4", description: "Scheduled report generation and email delivery", priority: 'Low' },
    ],
    techStack: {
      frontend: ["SvelteKit", "TypeScript", "D3.js"],
      backend: ["Python", "Flask"],
      database: ["Snowflake", "ClickHouse"],
      otherTools: ["Airflow", "Docker", "Pandas"],
    },
    marketAnalysis: "Internal tools market is focused on increasing efficiency. Key selling points are ease of use, powerful features, and seamless integration with existing company data stacks.",
    competitors: ["Tableau", "PowerBI", "Looker", "Metabase"],
  },
  {
    projectName: "E-commerce Platform",
    shortDescription: "A feature-rich e-commerce platform with a product catalog, shopping cart, and secure checkout process.",
    businessGoals: "Drive online sales, increase customer retention, and provide a seamless shopping experience.",
    technicalGoals: "Ensure high availability during peak traffic, secure payment processing, and fast page load times (Core Web Vitals).",
    targetUsers: ["Online Shoppers", "Store Administrators"],
    numberOfFeatures: 20,
    estimatedScale: "$80K-$200K",
    timeline: "7-10 months",
    coreRequirements: [
      { id: "1", description: "Product catalog with categories, filtering, and search", priority: 'High' },
      { id: "2", description: "Shopping cart and multi-step checkout flow", priority: 'High' },
      { id: "3", description: "Integration with a payment gateway (e.g., Stripe, PayPal)", priority: 'High' },
      { id: "4", description: "Order management dashboard for administrators", priority: 'Medium' },
    ],
    techStack: {
      frontend: ["Next.js", "TypeScript", "Redux Toolkit"],
      backend: ["Node.js", "Express.js", "Stripe SDK"],
      database: ["MongoDB"],
      otherTools: ["Vercel", "Docker", "Jest"],
    },
    marketAnalysis: "The e-commerce market is highly competitive. Differentiation can be achieved through niche products, superior user experience, or building a strong brand community.",
    competitors: ["Shopify", "BigCommerce", "WooCommerce", "Magento"],
  },
  {
    projectName: "B2B SaaS Platform",
    shortDescription: "A multi-tenant SaaS application with subscription billing and role-based access control.",
    businessGoals: "Acquire and retain business customers through a valuable and reliable service, based on a recurring revenue model.",
    technicalGoals: "Build a secure, scalable multi-tenant architecture. Implement a reliable subscription and billing system.",
    targetUsers: ["Business Users", "Team Admins", "Company Owners"],
    numberOfFeatures: 35,
    estimatedScale: "$150K-$500K",
    timeline: "9-12 months",
    coreRequirements: [
      { id: "1", description: "User authentication with team/organization support", priority: 'High' },
      { id: "2", description: "Subscription plans and billing integration (e.g., Chargebee, Stripe)", priority: 'High' },
      { id: "3", description: "Role-Based Access Control (RBAC) within teams", priority: 'High' },
      { id: "4", description: "A core feature specific to the SaaS product (e.g., project management, CRM)", priority: 'High' },
    ],
    techStack: {
      frontend: ["React", "Vite", "Tailwind CSS"],
      backend: ["Ruby on Rails", "Sidekiq"],
      database: ["PostgreSQL"],
      otherTools: ["Heroku", "Stripe Billing", "RSpec"],
    },
    marketAnalysis: "B2B SaaS is about solving a specific business problem more efficiently than existing solutions. Customer support and reliability are paramount. The sales cycle is longer, but customer lifetime value is higher.",
    competitors: ["Salesforce", "Atlassian Jira", "HubSpot", "Various niche competitors"],
  },
  {
    projectName: "AI/ML Model API Service",
    shortDescription: "A scalable API service for serving a machine learning model for tasks like image recognition or NLP.",
    businessGoals: "Provide a reliable, high-performance API for developers to integrate AI capabilities into their applications.",
    technicalGoals: "Low-latency model inference, high throughput, robust API key management, and easy deployment.",
    targetUsers: ["Developers", "Data Scientists"],
    numberOfFeatures: 10,
    estimatedScale: "$40K-$120K",
    timeline: "3-5 months",
    coreRequirements: [
      { id: "1", description: "A secure API endpoint for model inference", priority: 'High' },
      { id: "2", description: "API key authentication and usage tracking/rate limiting", priority: 'High' },
      { id: "3", description: "Infrastructure for model deployment and versioning", priority: 'Medium' },
      { id: "4", description: "Clear API documentation for developers", priority: 'High' },
    ],
    techStack: {
      frontend: [],
      backend: ["Python", "FastAPI", "Go", "NVIDIA Triton Inference Server", "Pytorch/TensorFlow"],
      database: ["Redis (for caching)"],
      otherTools: ["Docker", "Kubernetes/SageMaker", "Prometheus", "Grafana"],
    },
    marketAnalysis: "The AI API market is rapidly growing. Success hinges on the quality and uniqueness of the underlying model, as well as the reliability and ease of use of the API.",
    competitors: ["OpenAI API", "Hugging Face Inference API", "Google Cloud AI", "AWS AI Services"],
  },
];
